apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-docker-kubernetes
  template:
    metadata:
      labels:
        app: express-docker-kubernetes
    spec:
      containers:
      - name: express-docker-kubernetes
        image: aakashgaikwad/capstone1python:v1
        ports:
        - containerPort: 3000